booking/urls.py
from . import views
from django.urls import path, reverse

urlpatterns = [
    path('', views.Booking.as_view(), name='booking'),
    path('booking/', views.CreateBooking.as_view(), name='add_booking'),
    path('view-booking/', views.BookingList.as_view(), name='view_booking'),
    path(
        'delete/<slug:pk>/', views.DeleteBooking.as_view(),
        name='delete_booking'
        ),
    path('edit/<slug:pk>/', views.EditBooking.as_view(), name='edit_booking'),
    path(
        'search-booking/', views.SearchBooking.as_view(),
        name='search_booking'
        ),
]

cultureschool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("studyalong.urls"), name="studyalong-urls"),
    path("mybooking/", include("booking.urls"), name="booking-urls"),
    path("faq/", include("faq.urls"), name="faq-urls"),
    path("accounts/", include("allauth.urls")),
]

faq/urls.py
from . import views
from django.urls import path, reverse

urlpatterns = [
    path('', views.Faqlist.as_view(), name='faq'),
    path('post-faq/', views.Postquestion.as_view(), name='ask_faq'),
    path('ans-faq/<slug:pk>/', views.Ansquestion.as_view(), name='ans_faq'),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from studyalong.models import Course
from datetime import datetime
from django.utils.timezone import now

# Create your models here.

# Choice fields
COURSES = (
           ("Indian Classical", "Indian Classical"),
           ("Indian Bollywood", "Indian Bollywood"),
           ("Yoga Dance", "Yoga Dance"), ("Street Dance", "Street Dance"),
           ("Ballet Dance", "Ballet Dance"),
           ("Zumba dance", "Zumba dance"), ("Odissi", "Odissi")
           )


class Booking(models.Model):
    """ Model to book a course """
    booking_name = models.CharField(max_length=25)
    booked_date = models.DateTimeField(default=now, editable=True)
    personal_number = models.CharField(max_length=10)
    course = models.CharField(max_length=30, choices=COURSES)

    class Meta:
        """ Order by booking_date """
        ordering = ['course']

    def __str__(self):
        return str(self.course)


class Bookcourse(models.Model):
    """ Model to book a course """
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="booking_user")
    booking_name = models.CharField(max_length=25)
    booked_date = models.DateTimeField(default=now, editable=True)
    dob = models.DateField(max_length=8, default=False)
    spring_term = models.BooleanField(default=False)
    autumn_term = models.BooleanField(default=False)
    course = models.CharField(max_length=30, choices=COURSES)

    class Meta:
        """ Order by booking_date """
        ordering = ['booked_date']

    def __str__(self):
        return str(self.course)

booking/forms.py
from django import forms
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from .models import Booking, Bookcourse
from django.contrib.auth.models import User


class SearchForm(forms.ModelForm):
    """ Form to search a Booking"""
    class Meta:
        model = Bookcourse
        fields = ['booking_name']
        labels = {
            'booking_name': 'Full Name'
        }


class BookingForm(forms.ModelForm):
    """ Form to create a Booking"""
    class Meta:
        model = Bookcourse
        fields = [
                 'booking_name', 'course', 'dob', 'spring_term', 'autumn_term'
        ]
        booking_name = forms.CharField()
        spring_term = forms.CheckboxInput()
        autumn_term = forms.CheckboxInput()

        labels = {
            'username': 'Username',
            'booking_name': 'Full Name',
            'dob': 'Date Of Birth',
            'course': 'choose the course',
        }

        widgets = {'dob': DateInput(attrs={'type': 'date'})}

booking/views.py
from datetime import datetime
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib import messages
from .models import Booking, Bookcourse
from .forms import BookingForm, SearchForm
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin


# Create your views here.

class BookingList(generic.ListView):
    """ Read Booking view """
    model = Bookcourse
    queryset = Bookcourse.objects.order_by("-course")
    template_name = "booking_detail.html"


class CreateBooking(LoginRequiredMixin, CreateView):
    """ Create Booking View """
    model = Bookcourse
    form_class = BookingForm
    template_name = "create_booking.html"
    success_url = '/mybooking/'

    def form_valid(self, form):
        form.instance.username = self.request.user
        name = form.cleaned_data['booking_name']
        course = form.cleaned_data['course']
        dob = form.cleaned_data['dob']
        check_booking = (Bookcourse
                         .objects
                         .filter(booking_name=name, course=course))
        check_total = Bookcourse.objects.filter(course=course).count()
        today = datetime.today()
        age = int(today.year) - int(dob.year)
        if check_booking.exists():
            messages.success(
                self.request,
                f'Booking already exists for {name} in {course}.'
                f'Please go to MANAGE MY BOOKING'
                )
            return super(CreateBooking, self).form_invalid(form)
        if check_total == 10:
            messages.success(
                self.request,
                f'The {course} course is full'
                )
            return super(CreateBooking, self).form_invalid(form)
        if age < 5:
            messages.success(
                self.request,
                f'Minimum age to join a course is 5.{name} is welcome later'
                )
            return super(CreateBooking, self).form_invalid(form)
        else:
            obj = Bookcourse.objects.latest('id')
            messages.success(
                self.request,
                f'{obj} Course Booked Successfully.'
            )
        return super(CreateBooking, self).form_valid(form)


class EditBooking(SuccessMessageMixin,
                  LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ Edit a booking """
    model = Bookcourse
    template_name = "edit_booking.html"
    form_class = BookingForm
    success_url = '/mybooking/'
    success_message = "Booking updated Successfully"

    def test_func(self):
        return self.request.user == self.get_object().username


class DeleteBooking(LoginRequiredMixin,
                    SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    """ Delete a booking """
    model = Bookcourse
    template_name = "booking_confirm_delete.html"
    success_url = '/mybooking/'
    success_message = "Booking deleted Successfully"

    def test_func(self):
        return self.request.user == self.get_object().username


class Booking(generic.ListView):
    """Booking view """
    model = Bookcourse
    template_name = "booking.html"


class SearchBooking(ListView):
    """Searcg a booking view """
    model = Bookcourse
    template_name = "search_booking.html"
    context_object_name = 'bookinglist'

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset = (Bookcourse
                    .objects
                    .filter(booking_name__icontains=query)
                    .order_by("-booked_date"))
        return queryset

booking/templates/booking.html
{% extends "base.html" %}
{% load static %}

{% block content %}


{% block css %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        type="text/css">
{% endblock %}

<div class="row">
        <div class="col s12 center-align">
            <a href="{% url 'add_booking' %}" class="btn-large light-blue darken-2">
                Book a Course <i class="fas fa-plus-square right"></i>
            </a>
        </div>
</div>
<div class="row">
        <div class="col s12 center-align">
            <a href="{% url 'view_booking' %}" class="btn-large light-blue darken-2">
                Manage my booking<i class="fas fa-plus-square right"></i>
            </a>
        </div>
</div>
    {% if user.is_superuser %}
<div class="container">
    <form  action="{% url 'search_booking' %}" method="GET"  class="p-2 form">
        <h4 class="text-center">Find a booking</h4>
        {% csrf_token %}
        <input class="text-center" type="text" name="q" placeholder="Enter Full Name">
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Find</button>
        </div>
    </form>
</div>
    {% endif %}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <strong>  {{ message }} </strong>
    {% endfor %}
</ul>
{% endif %}

{% endblock content %}

booking/templates/booking_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <h1 class="text-center">Confirm Booking Deletion</h1>
    <div class="d-flex justify-content-center pt-3"></div>
      <form method="POST" class="text-center">
        {% csrf_token %}
        <p> Are you sure you want delete {{booking.booking_name}}?</p>
        <input type="submit" value="confirm"  class="btn btn-primary w-25">
      </form>
    </div>
</div>

{%endblock%}

booking/templates/booking_detail.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="col-12 mt-3 left">
    <div class="row">
        {% for bookcourse in bookcourse_list %}
        {% if request.user == bookcourse.username %}
        <div class="col-md-4 mt-10 p-1">
            <div class="card mb-4">
                <div class="card-body">
                    <p> {{ bookcourse.course }} booked by {{ bookcourse.username }} on  {{ bookcourse.booked_date }} </p>
                    <a href="{% url 'delete_booking'  bookcourse.id %}" class="btn btn-primary w-25">Delete</a>
                    <a href="{% url 'edit_booking'  bookcourse.id %}" class="btn btn-primary w-25">Edit</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

booking/templates/booking_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        type="text/css">
    <title>Booking</title>
</head>
<body>
    <h2>Manage your bookings</h2>
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>
    <div class="row">
        <div class="col s12 center-align">
            <a href="{% url 'add_booking' %}" class="btn-large light-blue darken-2">
                Book a Course <i class="fas fa-plus-square right"></i>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col s12 center-align">
            <a href="{% url 'edit_booking' %}" class="btn-large light-blue darken-2">
                Edit booking<i class="fas fa-plus-square right"></i>
            </a>
        </div>
    </div>
</body>
</html>

booking/templates/create_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Create Booking</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form| crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Book Course</button>
        </div>
    </form>
    <ul class="messages">
        {% for message in messages %}
        <strong>  {{ message }} </strong>
        {% endfor %}
    </ul>
</div>

{%endblock%}

booking/templates/edit_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Edit Booking</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form| crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Confirm</button>
        </div>
    </form>
</div>

{%endblock%}

booking/templates/search_booking.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="col-12 mt-3 left">
    <h4>You are Logged in as {{ user.get_username }} </h4>
    <div class="row">
        {% for booking in bookinglist %}
        <div class="col-md-4 mt-10 p-1">
            <div class="card mb-4">
                <div class="card-body">
                    <p> {{ booking.course }} booked by {{ booking.username }} on  {{ booking.booked_date }} </p>
                    <a href="{% url 'delete_booking'  booking.id %}" class="btn btn-primary w-25">Delete</a>
                    <a href="{% url 'edit_booking'  booking.id %}" class="btn btn-primary w-25">Edit</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{%endblock%}