cultureschool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("studyalong.urls"), name="studyalong-urls"),
    path("mybooking/", include("booking.urls"), name="booking-urls"),
    path("faq/", include("faq.urls"), name="faq-urls"),
    path("accounts/", include("allauth.urls")),
]

faq/urls.py
from . import views
from django.urls import path, reverse

urlpatterns = [
    path('', views.Faqlist.as_view(), name='faq'),
    path('post-faq/', views.Postquestion.as_view(), name='ask_faq'),
    path('ans-faq/<slug:pk>/', views.Ansquestion.as_view(), name='ans_faq'),
]

faq/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.


class faq(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    question = models.TextField()
    answer = models.TextField(default="We will get back to you soon")

    class Meta:
        ordering = ["-question"]

    def __str__(self):
        return self.name

faq/forms.py
from django import forms
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from .models import faq
from django.contrib.auth.models import User


class QuestionForm(forms.ModelForm):
    """ Form to ask a question"""
    class Meta:
        model = faq
        fields = ['name', 'email', 'question']
        name = forms.CharField()
        email = forms.CharField()
        question = forms.CharField()

        labels = {
            'name': 'name',
            'email': 'Email',
            'question': 'question',
        }


class AnswerForm(forms.ModelForm):
    """ Form to answer a question"""
    class Meta:
        model = faq
        fields = ['answer']
        answer = forms.CharField()

        labels = {
            'answer': 'answer',
        }

faq/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import faq
from .forms import QuestionForm, AnswerForm
from django.contrib.auth.models import User

# Create your views here.


class Faqlist(ListView):
    """ Create Booking View """
    model = faq
    template_name = "faq.html"
    success_url = '/'


class Postquestion(CreateView):
    """ Create Booking View """
    model = faq
    form_class = QuestionForm
    template_name = "create_faq.html"
    success_url = '/faq/'


class Ansquestion(UpdateView):
    """ Create Booking View """
    model = faq
    form_class = AnswerForm
    template_name = "answer_faq.html"
    success_url = '/faq/'

faq/templates/answer_faq.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Answer FAQ</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form| crispy }}
        <div class="text-center">
            <button type="Submit" class="btn btn-primary mt-2">Submit</button>
        </div>
    </form>
</div>

{%endblock%}

faq/templates/create_faq.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Ask Culture School</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form| crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Post</button>
        </div>
    </form>
</div>

{%endblock%}

faq/templates/faq.html
{% extends "base.html" %}

{% block content %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        type="text/css">
{% endblock %}      
        {% for faq in faq_list %}
        <div class="container">
            <p class="faq-question">{{ faq.question }}</p>
            <p  class="faq-answer"> Ans : {{ faq.answer }} </p>
            {% if user.is_superuser %}
            <a href="{% url 'ans_faq' faq.id %}" class="btn-small light-blue darken-2">
            Answer</a>
            {% endif %}
        </div>
        {% endfor %}
    <div class="row">
        <div class="col s12 center-align">
            <a href="{% url 'ask_faq' %}" class="btn-large light-blue darken-2">
                Ask Culture School
            </a>
        </div>
    </div>

{% endblock %}